### ISSUE TITLE
Dual screen support?

### ISSUE THREAD

**Issue by Eldino162** [rocksdanister/rePaper#13]
Dual screen support?

**Comment by rocksdanister** [comment]
Use my other software "Lively" : https://github.com/rocksdanister/lively
I am not working on rePaper right now.

I did simple rain alternative for Lively: https://www.reddit.com/r/LivelyWallpaper/comments/ew5e3e/preview_web_wallpaper_input_test_3_rain/

**Comment by rocksdanister** [comment]
Duplicate: https://github.com/rocksdanister/rePaper/issues/6
