### ISSUE TITLE
 the program crashes when I try to choose a wallpaper from the system tray

### ISSUE THREAD

**Issue by DCC-AFK** [rocksdanister/rePaper#14]
I've just made a portable download on my pc. But after a couple of uses, the program crashes when I try to choose a wallpaper from the system tray. I deleted the files and reinstalled them but that didn't help. Here's my log file.

[output_log.txt](https://github.com/rocksdanister/rePaper/files/4880792/output_log.txt)

**Comment by rocksdanister** [comment]
turn off dxva

**Comment by DCC-AFK** [comment]
thank you very much!!!! You're the best<3
