### ISSUE TITLE
Error 4xx

### ISSUE THREAD

**Issue by Kazlehoff** [rocksdanister/rePaper#2]
currently, weather and tempature are not functioning. error 4xx shown next to temperature.

Using my own API key from Openweather website in the API key section.

![image](https://user-images.githubusercontent.com/52207847/60112971-cfb4a600-973e-11e9-896d-ee18d5d90bc4.png)

**Comment by Kazlehoff** [comment]
the error goes away when changing API key back to default.

**Comment by rocksdanister** [comment]
I tried different key, can't recreate the error. maybe there is blank space in your key when copy pasted.

**Comment by frastanl** [comment]
I had the same issue when I first got the API key.  You have to wait a couple hours before it becomes usable.  I waited and the issue went away with my personal key.
