### ISSUE TITLE
Stops working when clicking on desktop.

### ISSUE THREAD

**Issue by LEADERS22** [rocksdanister/rePaper#4]
Whenever i click on an icon or the desktop it self everything related to the program freezes and the weird thing is when clicking the taskbar everything goes back to normal.
-Using windows 7

**Comment by rocksdanister** [comment]
Can you try v0.4 & v0.3 , I think its because I made workerWOrig as progman in v0.5.1

**Comment by LEADERS22** [comment]
No luck. i tried every release.
-Could it be related to my pc

**Comment by rocksdanister** [comment]
can you also try this: https://github.com/rocksdanister/GBWallpaper
also when you turn on debug mode, what does it say for foreground process.
As a temp fix you can set that application when on desktop to "ignore"in Application Rules.

**Comment by LEADERS22** [comment]
-The same problem with GBwallpaper i have to click on the taskbar to play the game
-foreground process says Explorer.EXE
-Setting it to ignore didn't work. (C:\Windows\explorer.exe) that's what i set to ignore
-Just for few second after i start rePaper it works fine then it starts having this problem

**Comment by rocksdanister** [comment]
this might be your system.
As a temporary fix, Exit repaper & goto <Your UserName>\Saved Games\rePaper & open application_rules.xml

Add this entry:
`  <ApplicationRule>
    <processName>explorer.exe</processName>
    <sleep>false</sleep>
  </ApplicationRule>`

Also make sure under Pause settings -> "Other Application Focus" is disabled.
Let me know if it works.

**Comment by LEADERS22** [comment]
This keeps coming up when going to settings after adding the new entry
![1](https://user-images.githubusercontent.com/51100531/62838779-ed9f8100-bc80-11e9-858b-e05eee9d5fa5.PNG)
-Is this correct
![2](https://user-images.githubusercontent.com/51100531/62838810-42db9280-bc81-11e9-9603-208c02fb0715.PNG)

**Comment by rocksdanister** [comment]
replace everything in that xml file with this:

`<?xml version="1.0"?>
<ArrayOfApplicationRule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ApplicationRule>
    <processName>Discord</processName>
    <sleep>false</sleep>
  </ApplicationRule>
  <ApplicationRule>
    <processName>Photoshop</processName>
    <sleep>true</sleep>
  </ApplicationRule>
  <ApplicationRule>
    <processName>AfterFX</processName>
    <sleep>true</sleep>
  </ApplicationRule>
  <ApplicationRule>
    <processName>blender</processName>
    <sleep>true</sleep>
  </ApplicationRule>
  <ApplicationRule> <processName>explorer.exe</processName> <sleep>false</sleep> </ApplicationRule>
</ArrayOfApplicationRule>
`

**Comment by LEADERS22** [comment]
Thank you man it worked at last.
