### ISSUE TITLE
Useful suggestion spam

### ISSUE THREAD

**Issue by ThaUnknown** [rocksdanister/rePaper#5]
Settings:

Multi monitor:
Option to display same background on all monitors
Option to display different backgrounds on different monitors
Option to toggle clock, weather and particles on different monitors

Weather:
Options to toggle which data on weather is displayed like turn off wind/temp/location name etc

Clock:
Options to toggle second, minute and hour display on all clocks
Option to toggle between 12hr and 24hr formats

Positions:
Options to change positions of weather, clock and audio visualizer [in the future]

Misc options:
Option to change background inside options menu
Option to disable video pausing permamently
Option to toggle settings menu icon on taskbar
Option to toggle rePaper icon in toolbar

Will add more suggestions if needed ^^

**Comment by rocksdanister** [comment]
You can optionally use rainmeter to display weather, clock overlay. 

Can you explain the Misc options in more detail, I can't seem to follow.

**Comment by rocksdanister** [comment]
closing due to no response.
