### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by vrindarx** [rocksdanister/rePaper#8]
Please add an option to pause the video wallpaper everytime focus is lost from the desktop.
Like the included app rules, but an option to select every application.
.
I request you to do this, as rePaper on win10, for me, has high cpu usage, and I don't have any dedicated gpu for DXVA.
.
PLEASE!
Nice Work btw! Customizers appreciate it :)

**Comment by rocksdanister** [comment]
its already there, under Performance -> Pause -> Other Appliation Focus
